[Parsing data in input.gyro]
----------------------------------------------------------
INFO: Rotation effects with delta B_parallel are experimental.
----------------------------------------------------------
 -----------------------------------------------
 operational mode     : FIELD EIGENVALUE
 boundary conditions  : PERIODIC
 profiles             : FLAT
 geometry             : MODEL SHAPE
 electron_method      : ALL SPECIES GYROKINETIC
 fluctuations         : EM: (Phi,A_par,B_par)
 gyro_method          : GRID-BASED J0^2 POLARIZATION
 fluctuation output   : PHI( ) N( ) E( ) V( )                   
 source_method        : NO SOURCE
 pitch-angle coll.    : OFF
 z_eff_method         : Use Z_EFF from input.gyro
 nonlinear dynamics   : OFF
 linear diffusivity   : OFF
 -----------------------------------------------
----------------------------------------------------------
INFO: (GYRO) Initialized multi-threaded MPI
----------------------------------------------------------
----------------------------------------------------------
INFO: (GYRO) Forcing up-down symmetry (UDSYMMETRY_FLAG=1).
----------------------------------------------------------
----------------------------------------------------------
INFO: (GYRO) You are using TOROIDAL_REFERENCE=-1
----------------------------------------------------------
----------------------------------------------------------
INFO: (GYRO) TOROIDAL_REFERENCE reset to lowest nonzero mode.
----------------------------------------------------------
----------------------------------------------------------
INFO: (GYRO) nu_ii rescaled by: 0.000
----------------------------------------------------------
 ----------- SPARSE MATRIX STATS ---------------
   POISSON-AMPERE:     n>0           
         nonzeros:     4096
           values:    12352
          indices:    16513
       iterations:        1

  EXPLICIT AMPERE:     n>0           
         nonzeros:     1024
           values:     3104
          indices:     4161
       iterations:        1

 ---------------- PARLLELISM DIMENSIONS --------------------
 MPI tasks            :    2
 OpenMP threads       :    4
 ----------------- GRID DIMENSIONS -------------------------
 n_n                  :    1
 n_x                  :    4
 n_stack              :   28
 n_blend              :    8
 n_pass               :    4
 n_trap               :    4
 n_energy             :    8
 n_field              :    3
 --
 n_spec               :    2
 n_ion                :    2
 n_kinetic            :    2
 n_gk                 :    2
 indx_e               :    2
 --
 FIELD POINTS:        :        96
 DIST. POINTS:        :     14336
 --
 energy_max           :   6.000000
 dt                   :   0.200000
 --------------------- LOCAL PARAMETERS --------------------
  NOTE: use abs(SAFETY_FACTOR) as input
 # RADIUS [INPUT]     :   0.700000
 .RADIUS              :   0.700000
 .ASPECT_RATIO        :   1.650000
 .SHIFT               :  -0.375000
 .ZMAG                :   0.000000
 .DZMAG               :   0.000000
 .KAPPA               :   2.400000
 .S_KAPPA             :  -0.120000
 .DELTA               :   0.310000
 .S_DELTA             :   0.230000
 .ZETA                :   0.000000
 .S_ZETA              :   0.000000
 .SAFETY_FACTOR       :   3.000000
 .SHEAR               :   0.880000
 .RHO_STAR            :   0.001944
 .Z_EFF               :   1.000000
 .MACH                :   0.000000
 .PGAMMA              :   0.000000
 .GAMMA_E             :   0.000000
 .NU_EI               :   0.000000
 .IPCCW               :  -1.000000
 .BTCCW               :  -1.000000
 # Ion  1
 .NI_OVER_NE          :   1.000000
 .TI_OVER_TE          :   1.000000
 .DLNNDR              :   1.000000
 .DLNTDR              :   1.000000
 .Z                   :   1.000000
 (NU_II)              :   0.000000
 .MU                  :   1.000000
 # Electrons
 .DLNNDR_ELECTRON     :   1.000000
 .DLNTDR_ELECTRON     :   1.000000
 (Z_ELECTRON)         :  -1.000000
 .BETAE_UNIT          :   0.017000
 .MU_ELECTRON         :  60.000000
 ------------- LOCAL PARAMETERS (diagnostic) ---------------
 n_i*z_i - n_e:       :   0.000000
 r/R0                 :   0.424242
 b_unit               :   1.000000
 beta_unit_norm       :   0.034000
 betai_unit           :   0.017000
 betae_unit_norm      :   0.017000
 beta_*               :   0.068000
 alpha_MHD            :   1.009800
 lambda_*             :   0.000000
 volume (1/a^3)       :  36.589740
 omega_00 (c_s/a)     :   0.000000
 * Note that f = f_sim exp(i n omega0[r0] t)
 ----------- ALFVEN WAVE PARAMETERS (diagnostic) -----------
 (v_A/c_s)            :  10.845017
 Omega_TAE            :   1.095456
 Omega_A              :   2.190912
 ------------------- UPWIND PARAMETERS ---------------------
 radial_upwind        :   1.000000
 orbit_upwind         :   1.000000
 orbit_upwind (elec)  :   1.000000
 --------------- RADIAL DOMAIN PARAMETERS ------------------
 box_multiplier       :   1.000000
 L/a                  :   0.008838
 --
 explicit_damp        :   0 (  1.0000)
 --
 LEFT : r_a           :   0.695581
 LEFT : r_a_physical  :   0.695581
 NORM : r(ir_norm)    :   0.700000
 RIGHT: r_b_physical  :   0.702210
 RIGHT: r_b           :   0.702210
 ----------- PARALLELIZATION PARAMETERS --------
 (nek) per subgroup:  :        32
 (ine) per subgroup:  :        16
 ----------- TIME STEPPING PARAMETERS ----------
 time_skip            :     5
 restart_data_skip    :    10
 ----------- STABILITY PARAMETERS ----------------
 d/dtau Courant       :  23.241360
   d/dr Courant       :   1.430858
 ------------- CENTRAL WAVENUMBERS SIMULATED ---------------
     (k_y = nq/r, rho = rho_sD_unit)
 n =    30   k_y rho =  0.250 [ 0.250][ 0.250]
  
 min resolved k_x*rho_sD :  1.382301
 max resolved k_x*rho_sD :  1.382301
 --------------- CENTRAL BOX SIZE -----------------
 abs(Lx/rho_sD)       :     4.545455
 abs(Ly/rho_sD)       :    25.132741
 => abs(dx/rho_sD)    :     1.136364
 --------------------------------------------------
 ------------ GYRO-OPERATOR BANDWIDTH -------------
 => EXACT BESSEL.
 --------------------------------------------------
 Startup time         :   0.094273
 --------------------------------------------------
 PLEASE SEE: 
  - out.gyro.units for normalizing parameters
  - out.gyro.memory for memory usage
  - out.gyro.efficiency for parallelization efficiency
  - out.gyro.phase_space for velocity-space nodes and weights
 STATUS: clean exit                                                                      
