[Parsing data in input.gyro]
----------------------------------------------------------
INFO: Rotation effects with delta B_parallel are experimental.
----------------------------------------------------------
 -----------------------------------------------
 operational mode     : FIELD EIGENVALUE
 boundary conditions  : PERIODIC
 profiles             : FLAT
 geometry             : MODEL SHAPE
 electron_method      : ALL SPECIES GYROKINETIC
 fluctuations         : EM: (Phi,A_par,B_par)
 gyro_method          : ORIGINAL (INTEGRATED) POLARIZATION
 fluctuation output   : PHI( ) N( ) E( ) V( )                   
 source_method        : NO SOURCE
 pitch-angle coll.    : RBF r^3
 z_eff_method         : Use Z_EFF from input.gyro
 nonlinear dynamics   : OFF
 linear diffusivity   : RESPONSE FUNCTION
 -----------------------------------------------
----------------------------------------------------------
INFO: (GYRO) Initialized multi-threaded MPI
----------------------------------------------------------
----------------------------------------------------------
INFO: (GYRO) Forcing up-down symmetry (UDSYMMETRY_FLAG=1).
----------------------------------------------------------
----------------------------------------------------------
INFO: (GYRO) You are using TOROIDAL_REFERENCE=-1
----------------------------------------------------------
----------------------------------------------------------
INFO: (GYRO) TOROIDAL_REFERENCE reset to lowest nonzero mode.
----------------------------------------------------------
----------------------------------------------------------
INFO: (GYRO) nu_ii rescaled by: 0.000
----------------------------------------------------------
 ----------- SPARSE MATRIX STATS ---------------
   POISSON-AMPERE:     n>0           
         nonzeros:     2304
           values:     6960
          indices:     9313
       iterations:        1

  EXPLICIT AMPERE:     n>0           
         nonzeros:      576
           values:     1752
          indices:     2353
       iterations:        1

 ---------------- PARLLELISM DIMENSIONS --------------------
 MPI tasks            :    2
 OpenMP threads       :    4
 ----------------- GRID DIMENSIONS -------------------------
 n_n                  :    1
 n_x                  :    4
 n_stack              :   20
 n_blend              :    6
 n_pass               :    4
 n_trap               :    4
 n_energy             :    8
 n_field              :    3
 --
 n_spec               :    2
 n_ion                :    2
 n_kinetic            :    2
 n_gk                 :    2
 indx_e               :    2
 --
 FIELD POINTS:        :        72
 DIST. POINTS:        :     10240
 --
 energy_max           :   6.000000
 dt                   :   0.005000
 --------------------- LOCAL PARAMETERS --------------------
  NOTE: use abs(SAFETY_FACTOR) as input
 # RADIUS [INPUT]     :   0.500000
 .RADIUS              :   0.500000
 .ASPECT_RATIO        :   3.000000
 .SHIFT               :   0.000000
 .ZMAG                :   0.000000
 .DZMAG               :   0.000000
 .KAPPA               :   1.000000
 .S_KAPPA             :   0.000000
 .DELTA               :   0.000000
 .S_DELTA             :   0.000000
 .ZETA                :   0.000000
 .S_ZETA              :   0.000000
 .SAFETY_FACTOR       :   2.000000
 .SHEAR               :   1.000000
 .RHO_STAR            :   0.050000
 .Z_EFF               :   1.000000
 .MACH                :   0.000000
 .PGAMMA              :   0.000000
 .GAMMA_E             :   0.000000
 .NU_EI               :   0.250000
 .IPCCW               :  -1.000000
 .BTCCW               :  -1.000000
 # Ion  1
 .NI_OVER_NE          :   1.000000
 .TI_OVER_TE          :   1.000000
 .DLNNDR              :   1.000000
 .DLNTDR              :   3.000000
 .Z                   :   1.000000
 (NU_II)              :   0.000000
 .MU                  :   1.000000
 # Electrons
 .DLNNDR_ELECTRON     :   1.000000
 .DLNTDR_ELECTRON     :   6.000000
 (Z_ELECTRON)         :  -1.000000
 .BETAE_UNIT          :   0.020000
 .MU_ELECTRON         :  60.000000
 ------------- LOCAL PARAMETERS (diagnostic) ---------------
 n_i*z_i - n_e:       :   0.000000
 r/R0                 :   0.166667
 b_unit               :   1.000000
 beta_unit_norm       :   0.040000
 betai_unit           :   0.020000
 betae_unit_norm      :   0.020000
 beta_*               :   0.220000
 alpha_MHD            :   2.640000
 lambda_*             :   0.000000
 volume (1/a^3)       :  14.804407
 omega_00 (c_s/a)     :   0.000000
 * Note that f = f_sim exp(i n omega0[r0] t)
 ----------- ALFVEN WAVE PARAMETERS (diagnostic) -----------
 (v_A/c_s)            :   9.998611
 Omega_TAE            :   0.833218
 Omega_A              :   1.666435
 ------------------- UPWIND PARAMETERS ---------------------
 radial_upwind        :   2.000000
 orbit_upwind         :   0.000000
 orbit_upwind (elec)  :   0.000000
 --------------- RADIAL DOMAIN PARAMETERS ------------------
 box_multiplier       :   1.000000
 L/a                  :   0.008333
 --
 explicit_damp        :   0 (  1.0000)
 --
 LEFT : r_a           :   0.495833
 LEFT : r_a_physical  :   0.495833
 NORM : r(ir_norm)    :   0.500000
 RIGHT: r_b_physical  :   0.502083
 RIGHT: r_b           :   0.502083
 ----------- PARALLELIZATION PARAMETERS --------
 (nek) per subgroup:  :        32
 (ine) per subgroup:  :        16
 ----------- TIME STEPPING PARAMETERS ----------
 time_skip            :    10
 restart_data_skip    :    10
 ----------- STABILITY PARAMETERS ----------------
 d/dtau Courant       :   0.266350
   d/dr Courant       :   0.442220
 Log(RBF Cond. num.)  :   7.496808
 ------------- CENTRAL WAVENUMBERS SIMULATED ---------------
     (k_y = nq/r, rho = rho_sD_unit)
 n =    30   k_y rho =  6.000 [ 6.000][ 6.000]
  
 min resolved k_x*rho_sD : 37.699112
 max resolved k_x*rho_sD : 37.699112
 --------------- CENTRAL BOX SIZE -----------------
 abs(Lx/rho_sD)       :     0.166667
 abs(Ly/rho_sD)       :     1.047198
 => abs(dx/rho_sD)    :     0.041667
 --------------------------------------------------
 ------------ GYRO-OPERATOR BANDWIDTH -------------
 => EXACT BESSEL.
 --------------------------------------------------
 Startup time         :   0.079442
 --------------------------------------------------
 PLEASE SEE: 
  - out.gyro.units for normalizing parameters
  - out.gyro.memory for memory usage
  - out.gyro.efficiency for parallelization efficiency
  - out.gyro.phase_space for velocity-space nodes and weights
 STATUS: unconverged                                                                     
