[Parsing data in input.gyro]
 -----------------------------------------------
 operational mode     : INITIAL VALUE
 boundary conditions  : NONPERIODIC
 profiles             : FLAT
 geometry             : S-ALPHA
 electron_method      : ADIABATIC ELECTRONS
 fluctuations         : ELECTROSTATIC
 gyro_method          : ORIGINAL (INTEGRATED) POLARIZATION
 fluctuation output   : PHI( ) N( ) E( ) V( )                   
 integrator_method    : RK2
 source_method        : NO SOURCE
 pitch-angle coll.    : OFF
 z_eff_method         : Use Z_EFF from input.gyro
 nonlinear dynamics   : OFF
 linear diffusivity   : RESPONSE FUNCTION
 -----------------------------------------------
----------------------------------------------------------
INFO: (GYRO) Initialized multi-threaded MPI
----------------------------------------------------------
----------------------------------------------------------
INFO: (GYRO) Forcing up-down symmetry (UDSYMMETRY_FLAG=1).
----------------------------------------------------------
----------------------------------------------------------
INFO: (GYRO) You are using TOROIDAL_REFERENCE=-1
----------------------------------------------------------
----------------------------------------------------------
INFO: (GYRO) TOROIDAL_REFERENCE reset to lowest nonzero mode.
----------------------------------------------------------
----------------------------------------------------------
INFO: (GYRO) nu_ii rescaled by: 0.000
----------------------------------------------------------
----------------------------------------------------------
INFO: (GYRO) nu_ei rescaled by: 0.000
----------------------------------------------------------
 ----------- SPARSE MATRIX STATS ---------------
 EXPLICIT POISSON:     n>0           
         nonzeros:     3672
           values:    14112
          indices:    14833
       iterations:        1

 ---------------- PARLLELISM DIMENSIONS --------------------
 MPI tasks            :    2
 OpenMP threads       :    4
 ----------------- GRID DIMENSIONS -------------------------
 n_n                  :    1
 n_x                  :   12
 n_stack              :   20
 n_blend              :    6
 n_pass               :    4
 n_trap               :    4
 n_energy             :    8
 n_field              :    1
 --
 n_spec               :    2
 n_ion                :    1
 n_kinetic            :    1
 n_gk                 :    1
 indx_e               :    2
 --
 FIELD POINTS:        :        72
 DIST. POINTS:        :     15360
 --
 energy_max           :   6.000000
 dt                   :   0.100000
 --------------------- LOCAL PARAMETERS --------------------
  NOTE: use abs(SAFETY_FACTOR) as input
 # RADIUS [INPUT]     :   0.500000
 .RADIUS              :   0.501136
 .ASPECT_RATIO        :   3.000000
 .SHIFT               :   0.000000
 .ZMAG                :   0.000000
 .DZMAG               :   0.000000
 .KAPPA               :   1.000000
 .S_KAPPA             :   0.000000
 .DELTA               :   0.000000
 .S_DELTA             :   0.000000
 .ZETA                :   0.000000
 .S_ZETA              :   0.000000
 .SAFETY_FACTOR       :   2.000000
 .SHEAR               :   1.000000
 .RHO_STAR            :   0.002500
 .Z_EFF               :   1.000000
 .MACH                :   0.000000
 .PGAMMA              :   0.000000
 .GAMMA_E             :   0.000000
 .NU_EI               :   0.000000
 .IPCCW               :  -1.000000
 .BTCCW               :  -1.000000
 # Ion  1
 .NI_OVER_NE          :   1.000000
 .TI_OVER_TE          :   1.000000
 .DLNNDR              :   1.000000
 .DLNTDR              :   3.000000
 .Z                   :   1.000000
 (NU_II)              :   0.000000
 .MU                  :   1.000000
 ------------- LOCAL PARAMETERS (diagnostic) ---------------
 n_i*z_i - n_e:       :   0.000000
 r/R0                 :   0.167045
 b_unit               :   1.000000
 beta_unit_norm       :   0.000000
 betai_unit           :   0.000000
 betae_unit_norm      :   0.000000
 beta_*               :   0.000000
 alpha_MHD            :   0.000000
 lambda_*             :   0.000000
 volume (1/a^3)       :  14.804407
 omega_00 (c_s/a)     :   0.000000
 * Note that f = f_sim exp(i n omega0[r0] t)
 ------------------- UPWIND PARAMETERS ---------------------
 radial_upwind        :   1.000000
 orbit_upwind         :   1.000000
 --------------- RADIAL DOMAIN PARAMETERS ------------------
 box_multiplier       :   3.000000
 L/a                  :   0.025000
 --
 explicit_damp        :   1 (  1.0000)
 --
 LEFT : r_a           :   0.487500
 LEFT : r_a_physical  :   0.489773
 NORM : r(ir_norm)    :   0.501136
 RIGHT: r_b_physical  :   0.510227
 RIGHT: r_b           :   0.512500
 ----------- PARALLELIZATION PARAMETERS --------
 (nek) per subgroup:  :        32
 (ine) per subgroup:  :        48
 ----------- TIME STEPPING PARAMETERS ----------
 time_skip            :    10
 restart_data_skip    :    10
 ----------- STABILITY PARAMETERS ----------------
 d/dtau Courant       :   0.087854
   d/dr Courant       :   0.402555
 ------------- CENTRAL WAVENUMBERS SIMULATED ---------------
     (k_y = nq/r, rho = rho_sD_unit)
 n =    30   k_y rho =  0.300 [ 0.300][ 0.300]
  
 min resolved k_x*rho_sD :  0.628319
 max resolved k_x*rho_sD :  1.884956
 --------------- CENTRAL BOX SIZE -----------------
 abs(Lx/rho_sD)       :    10.000000
 abs(Ly/rho_sD)       :    20.943951
 => abs(dx/rho_sD)    :     0.833333
 --------------------------------------------------
 ------------ GYRO-OPERATOR BANDWIDTH -------------
 Ion 1                :     9.166667
 --------------------------------------------------
 ---------------- BUFFER WIDTH --------------------
 Ion 1                :     0.909091     0.909091
 WARNING: All buffer widths should be > 8.0
 --------------------------------------------------
 Startup time         :   0.084329
 --------------------------------------------------
 PLEASE SEE: 
  - out.gyro.units for normalizing parameters
  - out.gyro.memory for memory usage
  - out.gyro.efficiency for parallelization efficiency
  - out.gyro.phase_space for velocity-space nodes and weights
 STATUS: converged                                                                       
