[Parsing data in input.gyro]
----------------------------------------------------------
INFO: Rotation effects with delta B_parallel are experimental.
----------------------------------------------------------
 -----------------------------------------------
 operational mode     : INITIAL VALUE
 boundary conditions  : NONPERIODIC
 profiles             : FLAT
 geometry             : MODEL SHAPE
 electron_method      : IMPLICIT DRIFT-KINETIC ELECTRONS
 fluctuations         : EM: (Phi,A_par,B_par)
 gyro_method          : ORIGINAL (INTEGRATED) POLARIZATION
 fluctuation output   : PHI( ) N( ) E( ) V( )                   
 integrator_method    : IMEX2
 source_method        : NO SOURCE
 pitch-angle coll.    : OFF
 z_eff_method         : Use Z_EFF from input.gyro
 nonlinear dynamics   : ON
 nonlinear bracket    : DIRECT
 -----------------------------------------------
----------------------------------------------------------
INFO: (GYRO) Initialized multi-threaded MPI
----------------------------------------------------------
----------------------------------------------------------
INFO: (GYRO) Forcing up-down symmetry (UDSYMMETRY_FLAG=1).
----------------------------------------------------------
----------------------------------------------------------
INFO: (GYRO) You are using TOROIDAL_REFERENCE=-1
----------------------------------------------------------
----------------------------------------------------------
INFO: (GYRO) TOROIDAL_REFERENCE reset to lowest nonzero mode.
----------------------------------------------------------
----------------------------------------------------------
INFO: (GYRO) nu_ii rescaled by: 0.000
----------------------------------------------------------
 ----------- SPARSE MATRIX STATS ---------------
   POISSON-AMPERE:     n=0        n>0
         nonzeros:    14688     14688
           values:    56304     56304
          indices:    63944     63944
       iterations:        1         1

  EXPLICIT AMPERE:     n=0        n>0
         nonzeros:     1944      1944
           values:     6156      6156
          indices:     7921      7921
       iterations:        1         1

      TOTAL FIELD:     n=0        n>0
         nonzeros:    18360     18360
           values:    79512     79512
          indices:    77408     77408
       iterations:        2         2

 ---------------- PARLLELISM DIMENSIONS --------------------
 MPI tasks            :    2
 OpenMP threads       :    4
 ----------------- GRID DIMENSIONS -------------------------
 n_n                  :    2
 n_x                  :   12
 n_stack              :   20
 n_blend              :    6
 n_pass               :    4
 n_trap               :    4
 n_energy             :    6
 n_field              :    3
 --
 n_spec               :    2
 n_ion                :    1
 n_kinetic            :    2
 n_gk                 :    1
 indx_e               :    2
 --
 FIELD POINTS:        :       432
 DIST. POINTS:        :     46080
 --
 energy_max           :   6.000000
 dt                   :   0.050000
 --------------------- LOCAL PARAMETERS --------------------
  NOTE: use abs(SAFETY_FACTOR) as input
 # RADIUS [INPUT]     :   0.500000
 .RADIUS              :   0.502841
 .ASPECT_RATIO        :   3.000000
 .SHIFT               :   0.000000
 .ZMAG                :   0.000000
 .DZMAG               :   0.000000
 .KAPPA               :   1.000000
 .S_KAPPA             :   0.000000
 .DELTA               :   0.000000
 .S_DELTA             :   0.000000
 .ZETA                :   0.000000
 .S_ZETA              :   0.000000
 .SAFETY_FACTOR       :   2.000000
 .SHEAR               :   1.000000
 .RHO_STAR            :   0.002500
 .Z_EFF               :   1.000000
 .MACH                :   0.000000
 .PGAMMA              :   1.000000
 .GAMMA_E             :   0.000000
 .NU_EI               :   0.000000
 .IPCCW               :  -1.000000
 .BTCCW               :  -1.000000
 # Ion  1
 .NI_OVER_NE          :   1.000000
 .TI_OVER_TE          :   1.000000
 .DLNNDR              :   1.000000
 .DLNTDR              :   2.000000
 .Z                   :   1.000000
 (NU_II)              :   0.000000
 .MU                  :   1.000000
 # Electrons
 .DLNNDR_ELECTRON     :   1.000000
 .DLNTDR_ELECTRON     :   2.000000
 (Z_ELECTRON)         :  -1.000000
 .BETAE_UNIT          :   0.001000
 .MU_ELECTRON         :  60.000000
 ------------- LOCAL PARAMETERS (diagnostic) ---------------
 n_i*z_i - n_e:       :   0.000000
 r/R0                 :   0.167614
 b_unit               :   1.000000
 beta_unit_norm       :   0.002000
 betai_unit           :   0.001000
 betae_unit_norm      :   0.001000
 beta_*               :   0.006000
 alpha_MHD            :   0.072000
 lambda_*             :   0.000000
 volume (1/a^3)       :  14.804407
 omega_00 (c_s/a)     :   0.000000
 * Note that f = f_sim exp(i n omega0[r0] t)
 ----------- ALFVEN WAVE PARAMETERS (diagnostic) -----------
 (v_A/c_s)            :  44.721360
 Omega_TAE            :   3.726780
 Omega_A              :   7.453560
 ------------------- UPWIND PARAMETERS ---------------------
 radial_upwind        :   1.000000
 orbit_upwind         :   1.000000
 orbit_upwind (elec)  :   0.000000
 --------------- RADIAL DOMAIN PARAMETERS ------------------
 box_multiplier       :   5.000000
 L/a                  :   0.062500
 --
 explicit_damp        :   2 (  1.0000)
 --
 LEFT : r_a           :   0.468750
 LEFT : r_a_physical  :   0.480114
 NORM : r(ir_norm)    :   0.502841
 RIGHT: r_b_physical  :   0.519886
 RIGHT: r_b           :   0.531250
 ----------- PARALLELIZATION PARAMETERS --------
 (nek) per subgroup:  :        48
 (ine) per subgroup:  :        72
 ----------- TIME STEPPING PARAMETERS ----------
 time_skip            :    20
 restart_data_skip    :    10
 ----------- STABILITY PARAMETERS ----------------
 d/dtau Courant       :   2.663504
   d/dr Courant       :   0.081074
 ------------- CENTRAL WAVENUMBERS SIMULATED ---------------
     (k_y = nq/r, rho = rho_sD_unit)
 n =     0   k_y rho =  0.000 [ 0.000][ 0.000]
 n =    20   k_y rho =  0.200 [ 0.200][ 0.200]
  
 min resolved k_x*rho_sD :  0.251327
 max resolved k_x*rho_sD :  0.753982
 --------------- CENTRAL BOX SIZE -----------------
 abs(Lx/rho_sD)       :    25.000000
 abs(Ly/rho_sD)       :    31.415927
 => abs(dx/rho_sD)    :     2.083333
 --------------------------------------------------
 ------------ GYRO-OPERATOR BANDWIDTH -------------
 Ion 1                :    22.916667
 --------------------------------------------------
 ---------------- BUFFER WIDTH --------------------
 Ion 1                :     4.545455     4.545455
 WARNING: All buffer widths should be > 8.0
 --------------------------------------------------
 Startup time         :   0.201424
 --------------------------------------------------
 PLEASE SEE: 
  - out.gyro.units for normalizing parameters
  - out.gyro.memory for memory usage
  - out.gyro.efficiency for parallelization efficiency
  - out.gyro.phase_space for velocity-space nodes and weights
 STATUS: clean exit                                                                      
